# Generated by Django 4.1 on 2022-08-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
